2024-03-20 03:44:26,450 pypet.environment.Environment ERROR    Following runs of trajectory `dummy` did NOT complete: `run_00000000, run_00000001, run_00000002, run_00000003`
2024-03-20 03:44:26,625 pypet.storageservice.HDF5StorageService ERROR    Failed loading  `Trajectory dummy (`Setting up the pypet pipeline for our temporal model of character displacement. `, len:12): (config: <class 'pypet.naturalnaming.ConfigGroup'>), (parameters: <class 'pypet.naturalnaming.ParameterGroup'>), (results: <class 'pypet.naturalnaming.ResultGroup'>)`
2024-03-20 03:44:26,625 pypet.naturalnaming.NaturalNamingInterface ERROR    Error while auto-loading `tau1` under ``.
